import Head from 'next/head'
import Header from '../components/Header';
import Loading from '../components/Loading';
import UserList from '../components/UserList';
import { AppContext } from './Context';
import { useContext } from 'react'; 



export default function Home(): JSX.Element {
  const { loading, data, fetchData } = useContext(AppContext);
  return (
    <>
      <Head>
        <title>GitStalker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" bg-[#02040a] text-white">
          <Header />
          {loading ? (
            <Loading size='50' />
          ) : (
            <UserList data={data} fetchData={fetchData} />
          )}
        </div>
      </main>
    </>
  )
}
