import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {gql,useQuery} from '@apollo/client'

const AllLinkQuery = gql`
  query MyQuery {
        countries {
          code
          currency
          name
        }
  }
`



export default function Home() {
  
  const { loading, error, data } = useQuery(AllLinkQuery);

  if (loading) return <p>Loading...</p>;

  if (error) return <p>Error : {error.message}</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data.countries.map(({code,currency,name})=>{
          return(<><p>{code}</p><p>{currency}</p><p>{name}</p></>)
        })}
      </main>
    </>
  )
}
